import {
  fetchTranscript,
  listCaptionTracks
} from "../src/youtube.js";

const videoId = process.argv[2] ?? "M7lc1UVf-VE";

const info = await listCaptionTracks(videoId);
console.log(`Video: ${info.title || videoId}`);

for (const [index, track] of info.tracks.entries()) {
  console.log(
    `${index + 1}. ${track.languageName} (${track.languageCode}) - ${track.isAutoGenerated ? "auto" : "manual"}`
  );
}

try {
  const transcript = await fetchTranscript(videoId, info.tracks[0]);
  console.log("");
  console.log(`First track transcript length: ${transcript.length}`);
  console.log(transcript.slice(0, 300).replace(/\s+/g, " "));
} catch (error) {
  console.log("");
  console.log(`Transcript fetch failed: ${error.code ?? error.name}`);
  console.log(error.message);
}
