const TELEGRAM_TEXT_LIMIT = 3900;

export function formatTrackSource(track) {
  return track.isAutoGenerated
    ? "автоматически сгенерированы YouTube"
    : "загружены вручную на YouTube";
}

export function formatTrackShortSource(track) {
  return track.isAutoGenerated ? "авто" : "вручную";
}

export function formatTrackLabel(track) {
  return `${track.languageName} (${track.languageCode}) — ${formatTrackSource(track)}`;
}

export function formatButtonLabel(track) {
  const label = `${track.languageName} (${track.languageCode}) - ${formatTrackShortSource(track)}`;

  if (label.length <= 60) {
    return label;
  }

  return `${track.languageCode} - ${formatTrackShortSource(track)}`;
}

export function buildLanguageChoiceMessage({ title, tracks }) {
  const heading = title
    ? `Нашёл несколько дорожек субтитров для видео:\n${title}`
    : "Нашёл несколько дорожек субтитров.";

  const options = tracks
    .map((track, index) => `${index + 1}. ${formatTrackLabel(track)}`)
    .join("\n");

  return `${heading}\n\nВыберите, на каком языке прислать расшифровку:\n\n${options}`;
}

export function buildTranscriptDocument({ videoId, title, track, transcript }) {
  const header = [
    "Полная расшифровка YouTube-видео",
    title ? `Название: ${title}` : null,
    `Видео: https://www.youtube.com/watch?v=${videoId}`,
    `Язык: ${track.languageName} (${track.languageCode})`,
    `Источник субтитров: ${formatTrackSource(track)}`
  ].filter(Boolean);

  return `${header.join("\n")}\n\n${transcript}`;
}

export function buildTranscriptCaption({ track, title }) {
  const titlePart = title ? `${truncate(title, 120)}\n` : "";
  return `${titlePart}Язык: ${track.languageName} (${track.languageCode})\nСубтитры: ${formatTrackSource(track)}`;
}

export function shouldSendAsDocument(text) {
  return text.length > TELEGRAM_TEXT_LIMIT;
}

export function buildTranscriptFilename({ videoId, track, title }) {
  const source = track.isAutoGenerated ? "auto" : "manual";
  const prefix = sanitizeFilename(title || videoId).slice(0, 70) || videoId;

  return `${prefix}_${track.languageCode}_${source}.txt`;
}

export function buildInlineKeyboard(requestId, tracks) {
  return {
    inline_keyboard: tracks.map((track, index) => [
      {
        text: formatButtonLabel(track),
        callback_data: `yt:${requestId}:${index}`
      }
    ])
  };
}

function truncate(text, limit) {
  return text.length <= limit ? text : `${text.slice(0, limit - 1)}…`;
}

function sanitizeFilename(text) {
  return text
    .normalize("NFKD")
    .replace(/[\\/:*?"<>|]+/g, "_")
    .replace(/\s+/g, " ")
    .trim();
}
